# version: "3"
# services:
#   postgres:
#     build: ./postgres
#     ports:
#       - "5433:5432"
#     environment:
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: admin
#       POSTGRES_DB: vectordb
version: '3.8'

services:
  pgvector:
    image: ankane/pgvector:latest
    restart: always
    environment:
      POSTGRES_DB: eddy_langchain
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha_eddy
    ports:
      - "5432:5432"
    volumes:
      - ~/volumes/pgvector:/var/lib/postgresql/data
      